cmd/really/really.cpp
cmd/really/reallyTest.cpp
include/quicr/quicr_server.h
include/quicr/quicr_server_session.h
src/quicr_client_raw_session.cpp
src/quicr_server.cpp
src/quicr_server_raw_session.cpp
src/quicr_server_raw_session.h
test/fake_transport.h

This appears to be working okay with WxQ/new-qmedia, but the TTL will need some adjusting in conf server/manifest. Right now the TTL is set to 50ms, which should be fine, but apparently it's not fine.  It needs to be more like 100ms. The problem appears to be with picoquic taking too long a times that exceeds 50ms.  That's a bit crazy, so we need to dig into that. Regardless, that's unrelated to the pq/time-queue changes here.

Pass priority and TTL to transport

---

.github/workflows/cmake.yml
benchmark/message_buffer.cpp
include/quicr/encode.h
include/quicr/message_buffer.h
include/quicr/message_types.h
include/quicr/quicr_common.h
include/quicr/quicr_server_delegate.h
include/quicr/uvarint.h
src/CMakeLists.txt
src/encode.cpp
src/message_buffer.cpp
src/quicr_client_raw_session.cpp
src/quicr_client_raw_session.h
src/quicr_server_raw_session.cpp
src/quicr_server_raw_session.h
test/encode.cpp

Okay, this PR started off as me messing around on my time off. It ended up becoming a pretty large thing, though I think it's made MessageBuffer stronger.
The big parts here are that:
- Name and consequently Namespace are cheaper to write
- Message types and uintVar_t are in their own respective headers
- encode.h has been turned into what's its name implies: a header with encode/decode methods
- MessageBuffer has become more concrete, and hopefully slightly faster
- Span is being used now when passing vectors to write to the buffer, and when access an immutable view/slice of the buffer (to reduce copy)
For sure Name is noticeably cheaper, going from 34-40ns on average to write to the buffer before to 5-8ns on average (all on my machine, GH Actions tells a similar story though)

Improving speed of MessageBuffer writes.

---

include/quicr/quicr_client.h
include/quicr/quicr_client_session.h
src/quicr_client.cpp
src/quicr_client_raw_session.cpp
src/quicr_client_raw_session.h
test/quicr_client.cpp

A bit of context here: The crashes around `notify_pub_fragment` (an example shown in https://github.com/Quicr/WxQ/issues/152) seem to be caused by a race with deleting entries from the `sub_delegates` map, and trying to access the whole map in the notify.
A few things here:
- The `subscribe_state` map was being fully emptied by both the `QuicrClientRawSession` and `QuicrClientTransportDelegate` destructors, which doesn't make a whole lot of sense.
- The QuicrClientTransportDelegate was acting as a hollow shell of the session itself (one could argue this was the point of a delegate), but didn't actually do any real work itself, just turned around and called the session to do the work anyways (not very delegate-like).
The changes here:
- QuicrRawClientSession becomes the TransportDelegate …

Cleaning up client session arch to stop frag crash.

---

src/quicr_server_raw_session.cpp

This change was probably introduced in #81, which changed a lot of `.count()` checks to `.contains()` checks -- and had no testing to verify that we got the polarity right in changing them.  Note that the library is broken right now: The `publish_namespaces` map is never populated, so all published objects are dropped.

Fix the polarity of a containment check

---

include/quicr/message_types.h
src/encode.cpp
src/quicr_client_raw_session.cpp
src/quicr_server_raw_session.cpp
test/encode.cpp

* Renames quicr header `flags` to `priority`
* Sets quicr header priority correctly so that it's sent to remote/relay
* Other fixes based on offsite findings

Offsite changes, add priority end-to-end and update transport 

---

.github/workflows/cmake.yml
src/quicr_client_raw_session.cpp

Updates transport to add connection timeout and fix stream reset race condition. 
Stops subscribe from creating unidirectional streams. Subscribes should have not created those streams.

Add connect timeout and fix subscribe streams

---

src/quicr_client_raw_session.cpp
src/quicr_client_raw_session.h
src/quicr_server_raw_session.cpp
test/fake_transport.h

Initially only UDP uses this feature. QUIC transport sets delay to 0 for all objects.

Implements transport API support of per object pacing

---

src/metrics_exporter.cpp

I am occasionally seeing an unhandled exception during flushing of the batch if the submission fails due to, for example, a local network issue. 
This handles any submission errors and logs an error instead of crashing. 
```
* thread #23, stop reason = signal SIGABRT
frame #0: 0x0000000189e62a60 libsystem_kernel.dylib`__pthread_kill + 8
frame #1: 0x0000000105d22be8 libsystem_pthread.dylib`pthread_kill + 288
frame #2: 0x0000000189da7a20 libsystem_c.dylib`abort + 180
frame #3: 0x0000000189e51d30 libc++abi.dylib`abort_message + 132
frame #4: 0x0000000189e41fcc libc++abi.dylib`demangling_terminate_handler() + 320
frame #5: 0x0000000189ae01e0 libobjc.A.dylib`_objc_terminate() + 160
frame #6: 0x0000000189e510f4 libc++abi.dylib`std::__terminate(void (*)()) + 16
frame #7: 0x0000000189e54348 …
```

Handle metrics exceptions

---

cmd/really/reallyTest.cpp
include/quicr/quicr_client.h
src/quicr_client.cpp
src/quicr_client_raw_session.cpp
src/quicr_client_raw_session.h

Fixes a compare build error and adds chunk size to quicr client constructor. This allows clients to configure their stream chunk (aka fragment) size.  Zero will disable the feature and will not chunk/fragment.

Fix compare and add chunk_size to client constructor

---

src/quicr_client_raw_session.cpp

Fixes issues with datagram handling, updates picoquic to latest as of June 3rd, and adds transport config option to set priority bypass.

Fix recv datagram handling with no data context

---

cmd/really/really.cpp
include/quicr/quicr_server_delegate.h
src/quicr_server_raw_session.cpp
test/fake_transport.h
test/quicr_server.cpp

Relay needs to know if the received object was
via a reliable stream or datagram.

Add reliable flag to server publish object cb

---

include/moq/publish_track_handler.h
include/moq/server_publish_track_handler.h
include/moq/subscribe_track_handler.h
src/moq/publish_track_handler_base.cpp

Made track handlers only constructable as shared_ptr, adding noexcept, const, and constexpr keywords to track handler APIs.

Safety and Modernise

---

include/moq/detail/messages.h
include/moq/detail/transport.h
include/moq/publish_track_handler.h
src/moq/messages.cpp
src/moq/publish_track_handler.cpp
src/moq/transport.cpp
test/moq_messages.cpp

Adds extensible object headers in the form of `count` (varint) followed by `count` entries of `tag` (varint), `length` (varint) and `bytes` (of size `length`).

Add extensible object header encode/decode

---

include/moq/detail/transport.h
src/moq/transport.cpp
test/CMakeLists.txt
test/client.cpp

Looks like the spdloggers created by `Transport` need to be explicitly torn down. Added a test that will demonstrate the issue when the `Transport` destructor is defaulted, and passes now that it drops the created logger.

Fix spdlog teardown issue

---

include/quicr/detail/priority_queue.h
include/quicr/detail/time_queue.h
include/quicr/detail/transport.h
include/quicr/publish_track_handler.h
src/transport.cpp
src/transport_picoquic.cpp

Fixes stream race issue causing picoquic to close connections due to local error 5. 
Also added the following:
* Fixed debug logging in transport to be set when transport config enables debug
* Added reusable publish send object buffer to avoid needless allocations for every object sent

Fix race issue with picoquic streams and other minor updates

---

cmd/examples/server.cpp
src/transport.cpp
src/transport_picoquic.cpp

Fixes the connection status reason type to correctly indicate the reason for the close.
Also adds a limit of 255 byte objects for `examples/qserver`.  Example `qserver` is for simple testing and demo/examples.  Full relay functionality is only maintained under https://github.com/quicr/laps

Indicate remote close on remote close in connection status

---

CMakeLists.txt

Webex services will build this repo inside build container, but cmake can't recognize it as Linux, Unix is fine.

cmake can't recognize container build environment as Linux

---

include/quicr/client.h

For one homer server, it should be able to connect different relay servers for the different conferences, this connection handle should be defined as one map identification in libquicr.

expose connection handle to external application

---

cmd/examples/server.cpp
include/quicr/common.h
src/server.cpp

Subscribe priority and order was not passed up to the server. This commit adds that.

Fix subscribe compare and add missing subscribe attributes

---

CMakeLists.txt

If a consumer of libquicr does an in-source CMake build (especially with a Unix Makefile generator), they will silently overwrite the project's custom Makefile and lose the targets defined there. I don't know of a valid use-case for an in-source build, so explicitly refusing to support it may reduce potential confusion. 
Discovered in #333

Disallow in-source builds

---

include/quicr/detail/quic_transport.h
include/quicr/detail/tick_service.h
include/quicr/detail/time_queue.h
include/quicr/server.h
src/transport_picoquic.cpp
src/transport_picoquic.h
test/tick_service.cpp

Quick performance improvements to reduce cpu by half, resulting in almost double scale.
* Change transport ConnData to use shared pointer for data. This allows the pointer to be used all the way to the transport without having allocate/copy it around. 
* In time queue:
*  Auto adjust the interval based on time duration to keep max buckets to 1000 or less. 
* Change O(n) `Clear()` to clear only the buckets that are in use. When the queue is being serviced, the result should only be a few buckets being cleared instead of up to 1000 for every pop. 
* Add tick_service as a parameter to Server constructor to support reusing a single tick service instance.

Perf improvements

---

src/server.cpp

Ensure we are still in some valid state before running callback.

Fix publisher callback ordering.

---

cmd/examples/client.cpp
cmd/examples/server.cpp
include/quicr/detail/data_storage.h
include/quicr/detail/messages.h
include/quicr/detail/priority_queue.h
include/quicr/detail/quic_transport.h
include/quicr/detail/safe_queue.h
include/quicr/detail/stream_buffer.h
include/quicr/detail/time_queue.h
include/quicr/detail/transport.h
include/quicr/metrics.h
include/quicr/publish_track_handler.h
include/quicr/server.h
include/quicr/subscribe_track_handler.h
src/CMakeLists.txt
src/client.cpp
src/messages.cpp
src/publish_track_handler.cpp
src/server.cpp
src/subscribe_track_handler.cpp
src/transport.cpp
src/transport_picoquic.cpp
src/transport_picoquic.h
test/data_storage.cpp
test/moq_messages.cpp

This PR changes transport to create a shared pointer vector upon receiving data. The shared pointer is then enqueued by move into a thread safe fifo queue.  A notification/callback is then called to inform the libquicr transport that there is data available. More data will continue to be added to the queue in the same fashion using shared pointers. 
The shared pointer vectors are referred to as **slices** of data because the data is of a stream of bytes, which does not have MoQ object bounds, hence a slice of data. 
The libquicr transport handling of received datagrams and stream data has moved to be processed under the Subscribe Handler. By default, the base subscribe handler class will do the work that was done before in libquicr transport to reassemble the slices into complete objects …

Shared memory access implementation

---

include/quicr/detail/stream_buffer.h
src/messages.cpp
test/moq_messages.cpp

This is a quick addition for interop of the "short" header extensions that consist of a single varint value when the extension type is even (`%2=0`). I would suggest we subsequently add a more advanced data structure for the `quicr::Extensions` type that can actually check the validity of extensions given these rules. Right now, it's still just a map of bytes and so the functions that accept it are naive to this change until they are put on/taken off the wire. 
I added a `ReadUintV` function to return the *encoded* varint for calls who want to inspect it. If that's not a good idea, no big deal, I'll change it back and construct in place.

Even header extension support

---

src/transport.cpp

This was causing messed up FETCH messages due to the uninitialised value. The parsing tests didn't catch this because they correctly initialise their structure with this field. Maybe there's a case for some consistent initialisation of these messages (especially as their structure changes in the draft and fields get added/removed). Maybe all the message fields could be const with buffer constructors and no default ctor?

Set missing fetch type

---

include/quicr/detail/messages.h
include/quicr/detail/stream_buffer.h
include/quicr/detail/transport.h
include/quicr/publish_track_handler.h
src/messages.cpp
src/subscribe_track_handler.cpp
src/transport.cpp
test/moq_data_messages.cpp

Closes #550 
We could better represent the modes in a fancier way if we want. I would also prefer that setting the serialisation flag of extensions if enforced at construction time, but this would require some changes in the stream buffer to forward emplace arguments if so, so I opted to defer that.

Add draft 11 subgroup header + logic

---

include/quicr/detail/ctrl_message_types.h
include/quicr/detail/ctrl_messages.h
src/ctrl_message_types.cpp
src/ctrl_messages.cpp
src/messages.cpp
test/moq_ctrl_messages.cpp
tools/draft_parser/moqt_parser/templates/cpp/MessageSpec_Source_End_tmpl.jinja2

- Add for parameters
- Consolidate uint64_t enum coding
- Move parameters to new structure
- Alter some of our parameters to be odd, so the encoding doesn't change. 
Will migrate extensions later. I know that test case is horrible.

Implement new KVP MoQ structure

---

include/quicr/detail/quic_transport.h

The previous value of `1000` doesn't work as a default because of control messages using a hardcoded TTL value of `2000`.

Update tconfig parameter

---

cmd/examples/client.cpp
cmd/examples/server.cpp
include/quicr/detail/quic_transport.h
src/transport_picoquic.cpp

This pull request introduces changes to enhance debugging capabilities for the `PicoQuicTransport` by enabling SSL key logging. The updates include configuring SSL key logging in the PicoQUIC library and setting the key log file from the environment.
Format is the same  as in picoquic: SSLKEYLOGFILE=<path_to_keylogfile>

Added SSL keylog, for easier tracing with wireshark

---

tools/draft_parser/moqt_parser/parsers.py

Without this fix, python 3.10 will report the following errors:
```
[ 79%] Built target picolog_t
Traceback (most recent call last):
File "/home/lal/volume/third_party/libquicr/tools/draft_parser/cmake/../main.py", line 5, in <module>
from moqt_parser import ProtocolMessageParser, CodeGenerator  # , TableParser
File "/home/lal/volume/third_party/libquicr/tools/draft_parser/moqt_parser/__init__.py", line 2, in <module>
from .parsers import ProtocolMessageParser
File "/home/lal/volume/third_party/libquicr/tools/draft_parser/moqt_parser/parsers.py", line 42
comp_name = f"{message_name}::{name.replace(" ","")}"
^
SyntaxError: f-string: unmatched '('
make[2]: *** [CMakeFiles/generate_moq_messages.dir/build.make:92: include/quicr/detail/ctrl_messages.h] Error 1 
```

Keep compatible with old version python

---

cmd/examples/client.cpp
cmd/examples/helper_functions.h
cmd/examples/server.cpp
cmd/qperf/qperf.cpp
cmd/qperf2/qperf.hpp
cmd/qperf2/qperf_pub.cc
include/quicr/client.h
include/quicr/detail/base_track_handler.h
include/quicr/detail/ctrl_message_types.h
include/quicr/detail/transport.h
include/quicr/publish_track_handler.h
include/quicr/server.h
include/quicr/subscribe_track_handler.h
include/quicr/track_name.h
src/client.cpp
src/server.cpp
src/transport.cpp
test/integration_test/test_server.cpp
test/integration_test/test_server.h
test/moq_ctrl_messages.cpp
test/track_handlers.cpp
test/track_namespace.cpp

I've altered track alias quite a bit here. I've removed the optional from the FTN structure, in lots of places it doesn't apply and gets set to null anyway, which I think is just cause for confusion. Instead, the alias is queried from the publish track handler with the request ID of the subscribe, and cannot be optional. The default implementation uses the full track hash regardless of request ID, keeping our existing behaviour.

Draft 12 compile

---

cmd/examples/server.cpp
src/transport.cpp

RemoveSubscribeTrack is called in various places, including upon subscribe error. In some cases we do not want to send unsubscribe. This change addresses when to send unsubscribe

Better handling of remove subscribe track/handler

---

src/transport.cpp

Quick hotfix for don't set subgroup on disallowed types - will come back to this.

Hotfix for new check

---

include/quicr/detail/transport.h
src/client.cpp
src/server.cpp
src/transport.cpp

Fix bug in `SUBSCRIBE_OK` message construction, where content exists having a value of `0` would result in a location of `{0, 0}` being encoded, rather than no location at all. I have changed the API so that the type system stops a bad combo of arguments. 
However, I think this is a good example of how something like #607 would allow us to encode these rules that aren't otherwise parsed from the spec and catch them as early as possible in deserialize, and also as a last chance check on serialize. 
Some known message vectors would also be great test suite addition - and probably a good addition as a draft appendix?

Fix subscribe ok

---

cmd/examples/client.cpp
cmd/examples/server.cpp
cmd/qperf/qperf.cpp
cmd/qperf2/qperf_sub.cc
include/quicr/detail/ctrl_message_types.h
include/quicr/fetch_track_handler.h
include/quicr/subscribe_track_handler.h
src/server.cpp
test/integration_test/integration_test.cpp
test/moq_ctrl_messages.cpp

Noticed these names and values weren't matching v12. (The `{2,1,3,4}` order was intentional to match the order they're described in the draft). 
>   There are 4 types of filters:
> 
>    Largest Object (0x2): The filter Start Location is {Largest
>    Object.Group, Largest Object.Object + 1} and Largest Object is
>    communicated in SUBSCRIBE_OK.  If no content has been delivered yet,
>    the filter Start Location is {0, 0}. There is no End Group - the
>    subscription is open ended.  Note that due to network reordering or
>    prioritization, relays can receive Objects with Locations smaller
>    than Largest Object after the SUBSCRIBE is processed, but these
>    Objects do not pass the Largest Object filter.
> 
>    Next Group Start (0x1): The filter start Location is {Largest
> …

Correct FilterType naming / values

---

include/quicr/detail/ctrl_message_types.h

Just removing the redundant `quicr::` qualifier from these operators.

Remove redundant qualifiers

---

cmd/examples/client.cpp
cmd/examples/server.cpp
include/quicr/client.h
include/quicr/detail/attributes.h
include/quicr/detail/transport.h
include/quicr/server.h
src/client.cpp
src/server.cpp
src/transport.cpp
test/integration_test/test_server.cpp
test/integration_test/test_server.h

- Few compile warnings from missing overrides / braces. 
- Break out `PublishAttributes` from `SubscribeAttributes` to remove the need for `TrackAlias` to be optional.

Fixup various warnings

---

CMakeLists.txt
cmd/examples/client.cpp
src/client.cpp
src/publish_track_handler.cpp
src/subscribe_track_handler.cpp
src/transport.cpp

Change subscribe update to start a new stream on `SendObject()`.  This is required to support peering/pipelining with mid-group joins. 
This change fixes pause/resume to correctly set forward value.

Subscribe Update starts new stream

---

CMakeLists.txt
cmd/examples/client.cpp
cmd/examples/server.cpp
include/quicr/subscribe_track_handler.h
src/server.cpp
src/subscribe_track_handler.cpp
src/transport.cpp

This adds back `SubscribeTrackHandler::RequestNewGroup()` method and implements it so that the server can forward it to  the publishers. qserver/qclient have been updated and support this.
Run qclient with the option `--new_group` when subscribing to test out the publisher seeing the new group request.

Expand new group request

---

include/quicr/detail/transport.h
src/transport.cpp
test/integration_test/integration_test.cpp

Fix strong reference cycle. The first commit adds a test to ensure a track handler has been cleaned up after unsubscribe. This should fail to show the existing issue of a use-count of `2` post-unsubscribe (the test plus the leaked ref in the lambda) instead of `1` (just the test owner). 
The second commit fixes the strong reference, makes the capture list more explicit, and fixes up a missing `const` that is needed to avoid marking the capture as mutable. I capture a weak_ptr here because the priority may have changed. The request ID probably not, but it's not const so...in theory...and we've already had to get the weak_ptr for priority anyway.

Fix subscribe update reference cycle

---

src/subscribe_track_handler.cpp
test/integration_test/integration_test.cpp

Protect these `std::function` calls with null checks. Add a test to ensure there is no crash when using a handler without a transport. I know there's discussion about rearchitecting this and this fix here is very minimal but it's still better than nothing so figured I'd throw it in.

Protect update func calls

---

cmd/examples/client.cpp
include/quicr/client.h
include/quicr/detail/base_track_handler.h
include/quicr/detail/transport.h
include/quicr/publish_track_handler.h
include/quicr/subscribe_track_handler.h
src/CMakeLists.txt
src/base_track_handler.cpp
src/client.cpp
src/publish_fetch_handler.cpp
src/publish_track_handler.cpp
src/server.cpp
src/subscribe_track_handler.cpp
src/transport.cpp
test/client.cpp
test/integration_test/integration_test.cpp

Remove function callback in publishers for sending data, and enforce that transport MUST be shared.

Ensure shared transport

---

src/server.cpp

Calling unsubscribe was causing errors and churn. The app, such as the relay, wasn't cleaning up properly either. The subscribe done callback should have been called upon receiving subscribe done.

Call subscribe done callback instead of unsubscribe

---

include/quicr/detail/ctrl_message_types.h
src/client.cpp
src/server.cpp

Stub in some basic protocol support for relative FETCH to the client. This is effectively the same as what we have in server, so I do think this can be refactored up to transport and shared between the two, but this gets us to protocol interop I think.

Add basic client FETCH protocol support

---

cmd/examples/client.cpp
include/quicr/detail/quic_transport.h
src/transport.cpp
src/transport_picoquic.cpp
src/transport_picoquic.h

This moves from libquicr created picoquic thread to picoquic creating the thread instead.  The advantage with this is that picoquic enables faster loop notifications than having to run the loop in a fast 500us loop.  This performs better and improves latency.
The changes also support adding multiple clients using the same quic instance. This will help dramatically with peering so that each outbound peer connection is not creating a new quic context. Another PR will expand on the client changes using network thread to expose a connect and disconnect API with the client.   
Resolves #697

Switch to use picoquic network thread api

---

src/transport_picoquic.cpp
src/transport_picoquic.h

Garbage values in non-initialised fields of this structure were causing bad accesses when used in Release builds - specifically the extra socket parameter. Added explicit init to resolve, figured no harm in doing it twice and being very explicit.

Fix non-zero initialisation
