Quicr/libquicr

- include/quicr/quicr_name.h
- include/quicr/quicr_namespace.h
- src/quicr_name.cpp
- test/name.cpp
Changes from #39 , only includes the name stuff, since this can safely go to main.
> Updating name to do some name arithmetic and added namesapce map.

- include/quicr/encode.h
- include/quicr/quicr_common.h
- src/encode.cpp
- test/encode.cpp
This is a v1 version of GET API  as a starting point. Once we experiment with the flows, we may want to revisit the right format and encoding of the same.
I will work on adding support for GET in the client/server API next
> fetch message v1

- src/quicr_client_raw_session.cpp
This may address the issue raised in https://github.com/Quicr/WxQ/issues/152
> Fix issue related to crash when erasing fragments

- cmd/really/reallyTest.cpp
- include/quicr/encode.h
- include/quicr/message_buffer.h
- include/quicr/message_types.h
- include/quicr/quicr_client.h
- include/quicr/quicr_client_session.h
- include/quicr/quicr_common.h
- include/quicr/quicr_server.h
- include/quicr/quicr_server_delegate.h
- include/quicr/quicr_server_session.h
- src/encode.cpp
- src/message_buffer.cpp
- src/quicr_client.cpp
- src/quicr_client_raw_session.cpp
- src/quicr_server.cpp
- test/encode.cpp
- test/fake_transport.h
- test/quicr_server.cpp
Just some cleanup and formatting. Adding to uintvar_t tests.
> Cleanup and format

- src/quicr_client_raw_session.cpp
- src/quicr_client_raw_session.h
Closes https://github.com/Quicr/libquicr/issues/62
> Fix deadlock.

- test/fake_transport.h
Update to latest transport main branch
> Transport Time Queue adjustments

- cmd/really/really.cpp
- cmd/really/reallyTest.cpp
- cmd/really/subscription.h
- include/quicr/message_types.h
- include/quicr/quicr_client.h
- include/quicr/quicr_client_delegate.h
- include/quicr/quicr_client_session.h
- include/quicr/quicr_common.h
- include/quicr/quicr_server.h
- include/quicr/quicr_server_delegate.h
- include/quicr/quicr_server_session.h
- src/encode.cpp
- src/quicr_client.cpp
- src/quicr_client_raw_session.cpp
- src/quicr_client_raw_session.h
- src/quicr_server.cpp
- src/quicr_server_raw_session.cpp
- src/quicr_server_raw_session.h
- test/encode.cpp
- test/fake_transport.h
- test/quicr_client.cpp
- test/quicr_server.cpp
Adds control stream and supports unidirectional, bidirectional, and creating new streams based on track, group, object, etc.
* Resolves #98
* Resolves #104
* Resolves #106
* Resolves #107
* Resolves #108
* Resolves #115
> Adds support for control streams, bidir/unidir streams, and changing of streams based on group, object, etc.

- include/quicr/quicr_common.h
- src/quicr_client_raw_session.cpp
> Update transport to main branch

- Makefile
- cmd/really/really.cpp
- cmd/really/reallyTest.cpp
- include/quicr/quicr_client.h
- include/quicr/quicr_client_session.h
- include/quicr/quicr_common.h
- include/quicr/quicr_server_delegate.h
- src/quicr_client.cpp
- src/quicr_client_raw_session.cpp
- src/quicr_client_raw_session.h
- src/quicr_server_raw_session.cpp
- src/quicr_server_raw_session.h
- test/fake_transport.h
- test/quicr_client.cpp
- test/quicr_server.cpp
> Add pause/resume feature support

- cmd/really/reallyTest.cpp
Updates transport to include reset and wait fixes
> Change to steady clock and update transport 

- .github/workflows/cmake.yml
- include/quicr/metrics_exporter.h
- src/metrics_exporter.cpp
- src/quicr_client_raw_session.cpp
- src/quicr_client_raw_session.h
- src/quicr_server_raw_session.cpp
- src/quicr_server_raw_session.h
- test/fake_transport.h
Adds peering metric support and updates transport to fix invalid drops and update picoquic to the `adjust-srtt` branch.
> Add peering metrics and fix invalid drops

- cmd/moq-example/client.cpp
- cmd/moq-example/server.cpp
- cmd/really/reallyTest.cpp
- test/quicr_server.cpp
Supports `TransportConfig` change from https://github.com/Quicr/transport/pull/156
> Support new tconfig structure

- .gitmodules
- cmd/moq-example/client.cpp
- cmd/moq-example/server.cpp
- cmd/really/really.cpp
- cmd/really/reallyTest.cpp
- dependencies/CMakeLists.txt
- include/quicr/metrics_exporter.h
- include/quicr/moq_instance.h
- include/quicr/moq_track_delegate.h
- include/quicr/quicr_client.h
- include/quicr/quicr_common.h
- include/quicr/quicr_server.h
- src/CMakeLists.txt
- src/metrics_exporter.cpp
- src/moq_instance.cpp
- src/quicr_client.cpp
- src/quicr_client_raw_session.cpp
- src/quicr_client_raw_session.h
- src/quicr_server.cpp
- src/quicr_server_raw_session.cpp
- src/quicr_server_raw_session.h
- test/fake_transport.h
- test/quicr_client.cpp
- test/quicr_server.cpp
Depends on https://github.com/Quicr/transport/pull/165
> Replacing cantina logger with spdlog.

- CMakeLists.txt
- cmd/examples/CMakeLists.txt
- cmd/examples/client.cpp
- cmd/examples/server.cpp
> client and server compile

- Makefile
- cmd/examples/client.cpp
- cmd/examples/helper_functions.h
- cmd/examples/server.cpp
- include/moq/client.h
- include/moq/detail/transport.h
- include/moq/server.h
- src/moq/server.cpp
- src/moq/transport.cpp
> MoQ client updates

- cmake/Lint.cmake
- cmd/examples/CMakeLists.txt
- include/moq/client.h
- include/moq/detail/base_track_handler.h
- include/moq/detail/stream_buffer.h
- include/moq/detail/time_queue.h
- include/moq/detail/transport.h
- include/moq/server.h
- include/moq/track_name.h
- src/CMakeLists.txt
- src/moq/client.cpp
- src/moq/messages.cpp
- src/moq/server.cpp
- src/moq/transport.cpp
- src/quic/transport_picoquic.cpp
Cleanup and adding some helper functions, addressing some clang-tidy comments.
> Cleanup & Refactor

- cmd/examples/client.cpp
- cmd/examples/server.cpp
- include/moq/subscribe_track_handler.h
This is a breaking API change.
> Add constness to callback spans

- CMakeLists.txt
Add aarch64 to supported processor list
> Add aarch64 to supported processor list

- src/client.cpp
> Cleanup if statements.

- include/quicr/detail/transport.h
- src/client.cpp
- src/server.cpp
- src/transport.cpp
> Replacing optional<weak_ptr> with shared_ptr.

- cmd/examples/client.cpp
- cmd/qperf/qperf.cpp
- include/quicr/detail/transport.h
- src/transport.cpp
> Fix duplicate ready status

- CMakeLists.txt
- src/transport.cpp
> Fix double lock causing server hangs upon abrupt client connection close

- src/transport_picoquic.cpp
> Update picoquic to latest master as of 10/10/2024

- include/quicr/client.h
- include/quicr/detail/messages.h
- include/quicr/detail/transport.h
- include/quicr/detail/uintvar.h
- include/quicr/metrics.h
- include/quicr/server.h
- src/client.cpp
- src/messages.cpp
- src/server.cpp
- src/transport.cpp
- test/moq_messages.cpp
- test/uintvar.cpp
> Prefix message length for control messages.

- include/quicr/detail/messages.h
- src/messages.cpp
- test/moq_messages.cpp
> SubGroup message encode/code

- cmd/examples/client.cpp
- cmd/examples/helper_functions.h
- include/quicr/detail/messages.h
- include/quicr/object.h
- src/messages.cpp
- src/transport.cpp
- test/moq_messages.cpp
> Ad support for Object Status encode/decode

- cmd/examples/helper_functions.h
- cmd/qperf/qperf.cpp
- include/quicr/detail/messages.h
- include/quicr/detail/transport.h
- include/quicr/track_name.h
- src/messages.cpp
- src/transport.cpp
- test/CMakeLists.txt
- test/moq_messages.cpp
- test/track_namespace.cpp
> Changing namespace to be a tuple.

- include/quicr/track_name.h
- test/track_namespace.cpp
> Revert "Fix bad prefix check and add more generic one."

- src/transport.cpp
I believe the track handler should be captured weakly into the publish object function in order for it to not hang around after being unpublished. 
I think I proved this with a `shared_ptr::use count` test that looks like: 
```cpp
auto handler = TestPublishTrackHandler::Create();
auto config = quicr::ClientConfig();
config.connect_uri = "moq://127.0.0.1:1234";
auto client = quicr::Client(config);
client.Connect();
CHECK_EQ(handler.use_count(), 1); // Just us, the creator.
client.PublishTrack(handler);
CHECK_GT(handler.use_count(), 1); // Us, plus whatever in the client holds onto it.
client.UnpublishTrack(handler);
CHECK_EQ(handler.use_count(), 1); // Without this fix, this would be 2. 
```
but I don't think it's a reliable enough test to add without a framework to either a mock a client …
> Capture publish handler weakly

- cmd/examples/client.cpp
- cmd/examples/server.cpp
- cmd/qperf2/qperf_sub.cc
- include/quicr/client.h
- include/quicr/common.h
- include/quicr/detail/messages.h
- include/quicr/detail/transport.h
- include/quicr/fetch_track_handler.h
- include/quicr/publish_track_handler.h
- include/quicr/server.h
- include/quicr/subscribe_track_handler.h
- src/client.cpp
- src/messages.cpp
- src/server.cpp
- src/transport.cpp
Related to https://github.com/Quicr/laps/issues/70
> Implementing Fetch

- cmd/qperf2/qperf_sub.cc
- cmd/qperf2/qperf_sub.hpp
Small set of change:
- reporting - formatting, delta calculations
- tear down condition
> Formatting, termination, added deltas

- include/quicr/detail/quic_transport.h
- include/quicr/detail/safe_queue.h
- include/quicr/fetch_track_handler.h
- include/quicr/hash.h
Fix up some minor doc related warnings that can show up in build output.
> Fixup doc warnings

- cmd/examples/server.cpp
- include/quicr/detail/base_track_handler.h
- include/quicr/detail/transport.h
- src/client.cpp
- src/server.cpp
- src/transport.cpp
> Adding latest group and object info to send sub ok.

- cmd/examples/client.cpp
- cmd/examples/server.cpp
- include/quicr/detail/messages.h
- include/quicr/detail/transport.h
- include/quicr/publish_track_handler.h
- include/quicr/server.h
- include/quicr/subscribe_track_handler.h
- src/client.cpp
- src/messages.cpp
- src/publish_track_handler.cpp
- src/server.cpp
- src/subscribe_track_handler.cpp
- src/transport.cpp
> Add New Group message

- cmd/examples/server.cpp
- test/track_namespace.cpp
> Adds qserver support for prefix matching

- include/quicr/detail/messages.h
- src/messages.cpp
- src/transport.cpp
- test/moq_messages.cpp
> Conform subscribe done to v8.

- include/quicr/detail/messages.h
- src/messages.cpp
> Fix object datagram encode/decode order.

- include/quicr/detail/messages.h
- src/messages.cpp
- test/moq_messages.cpp
> Conform announce cancel to v8.

- src/messages.cpp
> Parse fetch ok params.

- include/quicr/detail/messages.h
- src/messages.cpp
- test/moq_messages.cpp
> Conform SubOk to draft v8.

- include/quicr/detail/messages.h
- src/messages.cpp
> Remove unused path parameter.

- include/quicr/detail/messages.h
- src/messages.cpp
- src/transport.cpp
- test/moq_messages.cpp
> Add ObjectDatagramStatus message.

- cmd/examples/server.cpp
> Adding fetch cancel.

- cmd/examples/client.cpp
- cmd/examples/server.cpp
- include/quicr/client.h
- include/quicr/common.h
- include/quicr/detail/messages.h
- include/quicr/detail/transport.h
- include/quicr/server.h
- src/client.cpp
- src/messages.cpp
- src/server.cpp
- src/transport.cpp
- test/moq_messages.cpp
* Closes #409 
* Closes #358 
* Closes #451
> Subscribe announces implementation in libquicr, qclient and qserver

- include/quicr/detail/messages.h
- src/messages.cpp
- test/moq_messages.cpp
> Conform Fetch to v8.

- src/messages.cpp
> Encode announce params.

- include/quicr/detail/messages.h
- src/client.cpp
- src/messages.cpp
- src/server.cpp
- test/moq_messages.cpp
> Adding subscribes blocked.

- cmd/examples/client.cpp
- cmd/examples/server.cpp
- src/server.cpp
This fixes an issue with bad optional caused by new subscribe
> Handle new group changes better in example qclient/qserver

- cmd/examples/client.cpp
- cmd/examples/server.cpp
- include/quicr/detail/messages.h
- src/client.cpp
- src/messages.cpp
- src/server.cpp
- src/transport.cpp
- src/transport_picoquic.cpp
- test/moq_messages.cpp
Changes for draft-08 compliance and interoperability
> Interop 0224

- src/client.cpp
- src/messages.cpp
- src/server.cpp
Fixes crashes due to invalid message encoding
> Handle invalid message

- cmd/examples/CMakeLists.txt
- cmd/examples/client.cpp
Test that attempts to implement https://datatracker.ietf.org/doc/html/draft-jennings-moq-file-00
> [EXP] Add record and playback of moq messages.

- include/quicr/detail/base_track_handler.h
- include/quicr/detail/transport.h
- include/quicr/subscribe_track_handler.h
- src/client.cpp
- src/transport.cpp
- test/moq_ctrl_messages.cpp
Initial pass of adding `Location` 
#545
> Use Location structure

- include/quicr/detail/ctrl_message_types.h
- src/ctrl_message_types.cpp
- src/ctrl_messages.cpp
- src/transport.cpp
- test/moq_ctrl_messages.cpp
- tools/draft_parser/ctrl_messages.cpp
- tools/draft_parser/moqt_parser/templates/cpp/MessageSpec_Source_Structs_tmple.jinja2
Adds specific control message type and operators for wire encoding.
> Add ControlMessage encoder

- test/integration_test/integration_test.cpp
- test/integration_test/test_client.cpp
- test/integration_test/test_client.h
- test/integration_test/test_server.cpp
- test/integration_test/test_server.h
- Roundtrip test for subscribe
- Use promise/future for tests
> Subscribe integration

- cmd/dependencies/oss/cxxopts.hpp
- cmd/examples/client.cpp
- cmd/examples/server.cpp
- include/quicr/common.h
- include/quicr/detail/attributes.h
- include/quicr/detail/base_track_handler.h
- include/quicr/detail/transport.h
- include/quicr/publish_track_handler.h
- include/quicr/server.h
- include/quicr/subscribe_track_handler.h
- src/client.cpp
- src/publish_track_handler.cpp
- src/server.cpp
- src/subscribe_track_handler.cpp
- src/transport.cpp
- test/integration_test/integration_test.cpp
- test/integration_test/test_server.cpp
- test/integration_test/test_server.h
Adds support for PUBLISH while supporting backwards compatibility using ANNOUNCE flow. 
This PR also adds support for pause/resume in subscribe handler. Resolves #400 
Bumps version to draft 12
> Draft12 publish

- src/subscribe_track_handler.cpp
> Don't pop datagram type header

- src/publish_fetch_handler.cpp
- src/publish_track_handler.cpp
> Use FIN instead of RST on stream change/close

- include/quicr/detail/time_queue.h
- src/transport_picoquic.cpp
Dramatically improve the performance of priority queue and time queue by fixing the clear performance impact.
> Track buckets in use to improve clear performance

- cmd/examples/client.cpp
- include/quicr/detail/messages.h
- include/quicr/publish_track_handler.h
- include/quicr/subscribe_track_handler.h
- src/messages.cpp
- src/publish_track_handler.cpp
- src/subscribe_track_handler.cpp
- test/moq_data_messages.cpp
> Implement initial draft-14 stream object delta instead of object id

- CMakeLists.txt
- cmd/examples/client.cpp
- include/quicr/config.h
- include/quicr/detail/messages.h
- include/quicr/detail/quic_transport.h
- src/transport.cpp
- src/transport_picoquic.cpp
- src/transport_picoquic.h
* Add support for sugroups to start with unknown track alias for 3 seconds by default. This is to handle delayed subscribe OKs
> Address interop issues

- benchmark/priority_queue.cpp
- cmd/examples/client.cpp
- include/quicr/detail/priority_queue.h
- test/priority_queue.cpp
> Remove fake max for priorities and limit to size of uint8_t.

- include/quicr/detail/messages.h
> Protocol violation on bad message types
